"use server"

import { extract } from "@extractus/article-extractor"
import { OpenAI } from "openai"
import { trackGeneration, getUserUsageStats, canUserGenerateContent } from "@/lib/memberships"

type PlatformSelection = {
  twitter: boolean
  instagram: boolean
  linkedin: boolean
  email: boolean
}

type LimitsType = {
  twitter: number
  instagram: number
  linkedin: number
  email: number
}

type ModelProvider = "openai" | "anthropic";

// Get character limit from environment variable with fallback to 6000
const HARD_CHARACTER_LIMIT = process.env.MAX_CHARACTER_LIMIT 
  ? parseInt(process.env.MAX_CHARACTER_LIMIT, 10) 
  : 6000;

// Default character limits from environment variables
const DEFAULT_LIMITS = {
  twitter: parseInt(process.env.NEXT_PUBLIC_DEFAULT_LIMIT_TWITTER || '500', 10),
  instagram: parseInt(process.env.NEXT_PUBLIC_DEFAULT_LIMIT_INSTAGRAM || '2200', 10),
  linkedin: parseInt(process.env.NEXT_PUBLIC_DEFAULT_LIMIT_LINKEDIN || '3000', 10),
  email: parseInt(process.env.NEXT_PUBLIC_DEFAULT_LIMIT_EMAIL || '300', 10),
}

// Mock responses for development/preview when OpenAI API is not available
const mockResponses = {
  twitter: "This is a sample X post that would be generated by the AI. #content #repurposing",
  instagram:
    "This is a sample Instagram caption that would be generated by the AI.\n\nIt includes multiple lines to make it engaging!\n\n#instagram #content #repurposing",
  linkedin:
    "I'm excited to share this professional LinkedIn post that would be generated by the AI. It's designed to engage business professionals and includes a call to action.\n\nWhat are your thoughts on content repurposing? Let me know in the comments below!",
  email:
    "Check out our latest article on content repurposing! This email snippet is designed to get readers to click through to read more.",
}

// Create emoji versions of mock responses that are used only when useEmojis is true
const emojiMockResponses = {
  twitter: "✨ This is a sample X post that would be generated by the AI. #content #repurposing",
  instagram:
    "📱 This is a sample Instagram caption that would be generated by the AI.\n\nIt includes multiple lines and emojis to make it engaging! 🔥\n\n#instagram #content #repurposing",
  linkedin:
    "🚀 I'm excited to share this professional LinkedIn post that would be generated by the AI. It's designed to engage business professionals and includes a call to action.\n\nWhat are your thoughts on content repurposing? Let me know in the comments below! 💬",
  email:
    "📧 Check out our latest article on content repurposing! This email snippet is designed to get readers to click through to read more. ✨",
}

export async function fetchArticleContent(url: string): Promise<string> {
  try {
    // Validate URL format
    let validatedUrl: URL;
    try {
      validatedUrl = new URL(url);
      // Make sure it's http or https
      if (!['http:', 'https:'].includes(validatedUrl.protocol)) {
        throw new Error("URL must start with http:// or https://");
      }
    } catch (urlError) {
      throw new Error("Please enter a valid URL (e.g., https://example.com/article)");
    }

    // Extract article content using article-extractor
    const article = await extract(validatedUrl.toString());

    if (!article) {
      throw new Error("Could not extract content from the provided URL");
    }

    if (!article.content) {
      throw new Error("The article was found but no content could be extracted");
    }

    // Clean up the content to remove any remaining HTML and optimize token usage
    const title = article.title || "";
    let cleanContent = article.content || "";
    
    // Enhanced cleaning process to ensure all HTML is removed
    cleanContent = cleanContent
      // Remove any remaining HTML tags
      .replace(/<\/?[^>]+(>|$)/g, " ")
      // Replace HTML entities with their text equivalents
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, "\"")
      .replace(/&#39;/g, "'")
      // Normalize whitespace
      .replace(/\s+/g, " ")
      .replace(/\n\s*\n/g, "\n\n")
      .trim();
    
    // Extract the first 3 sentences as a summary for context saving
    const sentences = cleanContent.match(/[^.!?]+[.!?]+/g) || [];
    const summary = sentences.slice(0, 3).join(" ");
    
    // Optimize content length based on meaningful paragraphs
    const paragraphs = cleanContent.split("\n\n").filter(p => p.trim().length > 0);
    
    // Take only the most meaningful paragraphs (first few and last few)
    const maxParagraphs = 10; // Adjust based on typical article length
    let optimizedParagraphs;
    
    if (paragraphs.length <= maxParagraphs) {
      optimizedParagraphs = paragraphs;
    } else {
      // Take first paragraphs (typically most informative)
      const firstParagraphs = paragraphs.slice(0, Math.ceil(maxParagraphs * 0.7));
      // Take last paragraphs (typically conclusion)
      const lastParagraphs = paragraphs.slice(-(Math.floor(maxParagraphs * 0.3)));
      optimizedParagraphs = [...firstParagraphs, ...lastParagraphs];
    }
    
    // Construct the final cleaned content
    let result = `Title: ${title}\n\nSummary: ${summary}\n\nContent:\n${optimizedParagraphs.join("\n\n")}`;
    
    // Ensure result is within character limit
    if (result.length > HARD_CHARACTER_LIMIT) {
      result = result.substring(0, HARD_CHARACTER_LIMIT);
    }
    
    return result;
  } catch (error: any) {
    console.error("Error fetching article:", error);
    
    // Provide more specific error messages based on error type
    if (error.message.includes("ENOTFOUND") || error.message.includes("ETIMEDOUT")) {
      throw new Error("Could not connect to the website. Please check the URL and try again.");
    }
    
    if (error.message.includes("403")) {
      throw new Error("Access to this website is forbidden. The site may be blocking automated requests.");
    }
    
    if (error.message.includes("404")) {
      throw new Error("The article was not found. Please check the URL and try again.");
    }
    
    // Return either the custom error message or a generic one
    throw new Error(error.message || "Failed to fetch article content. Please check the URL and try again.");
  }
}

// Check if we're in a browser environment
const isBrowser = () => typeof window !== "undefined"

export async function generateContent(
  content: string,
  platforms: PlatformSelection,
  tone = "professional",
  customInstructions = "",
  limits?: LimitsType,
  useEmojis = false,
  modelProvider: ModelProvider = "openai",
): Promise<Record<string, string | any>> {
  // Enforce character limit
  if (content.length > HARD_CHARACTER_LIMIT) {
    content = content.substring(0, HARD_CHARACTER_LIMIT);
  }
  
  // Check if user has reached their generation limit
  try {
    // Use the dedicated function to check if user can generate content
    const canGenerate = await canUserGenerateContent();
    if (!canGenerate) {
      throw new Error("You've reached your daily generation limit. Please upgrade your plan to continue generating content.");
    }
  } catch (error: any) {
    if (error.message.includes("upgrade your plan")) {
      throw error;
    }
    // If there's another error with stats, continue without checking limits
    console.error("Error checking usage limits:", error);
  }

  const result: Record<string, string | any> = {}
  const prompts: Record<string, string> = {}

  // Build tone instruction
  let toneInstruction = ""
  let emojiInstruction = ""
  
  // Adjust emoji instruction to be more tone-specific
  if (useEmojis) {
    switch (tone) {
      case "professional":
        emojiInstruction = "Include a few subtle, professional emojis where appropriate (e.g., ✓, 📊, 📈, 💼, 🔍)."
        break
      case "casual":
        emojiInstruction = "Include friendly, conversational emojis to make the content more relatable (e.g., 😊, 👋, 💯, ✨, 👍)."
        break
      case "humorous":
        emojiInstruction = "Add playful and humorous emojis to enhance the lighthearted tone (e.g., 😂, 🤣, 😜, 🙌, 🎉)."
        break
      case "enthusiastic":
        emojiInstruction = "Use energetic and expressive emojis to convey excitement (e.g., 🔥, 💪, 🚀, ⚡, 🌟)."
        break
      case "informative":
        emojiInstruction = "Add occasional relevant emojis to highlight key information points (e.g., 📝, ℹ️, 💡, 🔎, 📌)."
        break
      default:
        emojiInstruction = "Include appropriate emojis to enhance the message."
    }
  }

  switch (tone) {
    case "professional":
      toneInstruction = "Use a professional, business-appropriate tone."
      break
    case "casual":
      toneInstruction = "Use a casual, conversational tone as if talking to a friend."
      break
    case "humorous":
      toneInstruction = "Use a light-hearted, humorous tone with appropriate jokes or puns."
      break
    case "enthusiastic":
      toneInstruction = "Use an enthusiastic, energetic tone with excitement."
      break
    case "informative":
      toneInstruction = "Use an informative, educational tone focusing on facts and insights."
      break
    default:
      toneInstruction = "Use a professional, business-appropriate tone."
  }

  // Fix how custom instructions are incorporated into prompts
  const customInstructionsText = customInstructions.trim() 
    ? `\nAdditional specific instructions: ${customInstructions.trim()}`
    : "";

  if (platforms.twitter) {
    prompts.twitter = `
      You are a social media expert. Create a concise, engaging X (formerly Twitter) post (max ${limits?.twitter || 280} characters) based on the following content.
      ${toneInstruction}
      Include relevant hashtags and make it shareable.
      ${customInstructionsText}
      
      Content to repurpose:
      ${content}
      
      Format your response using markdown formatting where appropriate.
      ${useEmojis ? emojiInstruction : "Do not include any emojis in the response. No emojis at all. None."}
    `
  }

  if (platforms.instagram) {
    prompts.instagram = `
      You are a social media expert. Create an engaging Instagram caption based on the following content.
      ${toneInstruction}
      Include relevant hashtags${useEmojis ? ", use emojis appropriately," : ""} and format it with line breaks for readability.
      Keep it under ${limits?.instagram || 2200} characters.
      ${customInstructionsText}
      
      Content to repurpose:
      ${content}
      
      Format your response using markdown. Use formatting like bold for emphasis, bullet points for lists, and proper line breaks.
      ${useEmojis ? emojiInstruction : "Do not include any emojis in the response. No emojis at all. None."}
    `
  }

  if (platforms.linkedin) {
    prompts.linkedin = `
      You are a professional content writer. Create a LinkedIn post based on the following content.
      ${toneInstruction}
      Make it insightful and engaging for a business audience. Include a call to action.
      Keep it under ${limits?.linkedin || 3000} characters.
      ${customInstructionsText}
      
      Content to repurpose:
      ${content}
      
      Format your response using markdown. Use formatting like bold for important points, bullet points for lists, and proper headings and paragraphs.
      ${useEmojis ? emojiInstruction : "Do not include any emojis in the response. No emojis at all. None."}
    `
  }

  if (platforms.email) {
    prompts.email = `
      You are an email marketing expert. Create a concise email snippet (max ${limits?.email || 300} characters) based on the following content.
      ${toneInstruction}
      Make it compelling and designed to encourage the reader to click through to read more.
      ${customInstructionsText}
      
      Content to repurpose:
      ${content}
      
      Format your response using markdown. Use formatting like bold for important points and proper paragraphs.
      ${useEmojis ? emojiInstruction : "Do not include any emojis in the response. No emojis at all. None."}
    `
  }

  // Only generate content for selected platforms
  const selectedPlatforms = Object.keys(prompts) as Array<keyof typeof prompts>

  if (selectedPlatforms.length === 0) {
    return {}
  }

  // Check if we're in a preview/development environment without API access
  const isPreviewOrMissingAPIKey = (modelProvider === "openai" && (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === "dummy")) || 
    (modelProvider === "anthropic" && (!process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_API_KEY === "dummy")) || 
    isBrowser()

  if (isPreviewOrMissingAPIKey) {
    console.log("Using mock responses for preview/development")
    // Return mock responses for selected platforms
    for (const platform of selectedPlatforms) {
      const mockResponseSet = useEmojis ? emojiMockResponses : mockResponses;
      result[platform] = mockResponseSet[platform as keyof typeof mockResponses] || `Sample ${platform} content would appear here.`
    }
    return result
  }

  try {
    // Process platforms one at a time using the selected model provider
    for (const platform of selectedPlatforms) {
      try {
        let generatedContent = "";
        
        if (modelProvider === "anthropic") {
          // Use Anthropic's Claude API
          generatedContent = await generateWithClaude(prompts[platform]);
        } else {
          // Use OpenAI's API (default)
          generatedContent = await generateWithOpenAI(prompts[platform]);
        }

        // Enforce character limits strictly
        const platformLimit = limits?.[platform as keyof typeof limits] || DEFAULT_LIMITS[platform as keyof typeof DEFAULT_LIMITS];
        if (generatedContent.length > platformLimit) {
          console.log(`Truncating ${platform} content from ${generatedContent.length} to ${platformLimit} characters`);
          generatedContent = generatedContent.substring(0, platformLimit);
        }

        result[platform] = generatedContent;
        
        console.log(`Generated content for ${platform} using ${modelProvider}, length: ${generatedContent.length}`);
        
        // Track this generation in the database with the content
        if (!isPreviewOrMissingAPIKey) {
          try {
            console.log(`Storing generation for ${platform} in database with model: ${modelProvider}`);
            // Track generation and return result for instant display - pass the model provider
            const trackResult = await trackGeneration(platform, generatedContent.length, generatedContent, modelProvider);
            
            if (trackResult && typeof trackResult === 'object' && 'id' in trackResult) {
              console.log(`✅ Store success for ${platform}, ID: ${(trackResult as {id: string | number}).id}`);
              
              // Store the database record ID with the generation
              // This will be useful for immediate updating of the history list
              if (!result._meta) result._meta = {};
              if (!result._meta.dbRecords) result._meta.dbRecords = {};
              result._meta.dbRecords[platform] = trackResult;
            } else {
              console.log(`❌ Store may have failed for ${platform}, no result returned`);
              
              // Try to diagnose the issue - run a direct test after a short delay
              setTimeout(async () => {
                try {
                  const testResponse = await fetch('/api/test-db');
                  const testResult = await testResponse.json();
                  console.log('Database diagnostic test result:', testResult);
                } catch (testErr) {
                  console.error('Failed to run diagnostic test:', testErr);
                }
              }, 500);
            }
          } catch (trackError) {
            console.error(`Error tracking generation for ${platform}:`, trackError);
            // Don't throw here, just log the error and continue
          }
        } else {
          console.log('Skipping database storage (preview mode or missing API key)');
        }
      } catch (error) {
        console.error(`Error generating content for ${platform} with ${modelProvider}:`, error)
        result[platform] = `Could not generate content for ${platform}. Please try again.`
      }
    }

    return result
  } catch (error) {
    console.error(`Error in content generation process with ${modelProvider}:`, error)

    // Fallback to mock responses if API initialization fails
    for (const platform of selectedPlatforms) {
      result[platform] = mockResponses[platform as keyof typeof mockResponses] || `Sample ${platform} content would appear here.`
    }

    return result
  }
}

// Generate content using OpenAI API
async function generateWithOpenAI(prompt: string): Promise<string> {
  // Initialize OpenAI client
  const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });

  // Set up API options
  const apiOptions = {
    model: "gpt-4o-2024-08-06", // Default model
    messages: [
      {
        role: "system" as const,
        content: "You are a content repurposing assistant. Your job is to create engaging content for various platforms based on the provided content.",
      },
      {
        role: "user" as const,
        content: prompt,
      },
    ],
    temperature: 0.7,
    max_tokens: 1024
  };

  const response = await openai.chat.completions.create(apiOptions);
  return response.choices[0]?.message?.content || "";
}

// Generate content using Anthropic's Claude API
async function generateWithClaude(prompt: string): Promise<string> {
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error("Anthropic API key is not configured");
  }

  // Prepare the Claude API request
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': process.env.ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-3-haiku-20240307', // Changed from Opus to Haiku for faster performance
      max_tokens: 1024,
      temperature: 0.7,
      system: "You are a content repurposing assistant. Your job is to create engaging content for various platforms based on the provided content.",
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(`Anthropic API error: ${errorData.error?.message || response.statusText}`);
  }

  const data = await response.json();
  return data.content[0]?.text || "";
}

